import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Atma } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { shadesOfPurple } from "@clerk/themes";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import { ClerkThemeProvider } from "@/components/providers/ClerkThemeProvider";

const atmaFont = Atma({
  variable: "--font-atma",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Watch Hub App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${atmaFont.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkThemeProvider>
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <Navbar />
            </header>
            {children}
            <ToastContainer
              position="bottom-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
              toastClassName="dark:bg-gray-800 dark:text-white"
              bodyClassName="dark:text-white"
            />
          </ClerkThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
