import { Atma } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthContextProvider from "@/context/AuthContext";

const atmaFont= Atma({
  variable: "--font-atma",
  subsets: ["latin"], 
  weight: ["300", "400", "500", "600", "700"], 
});


export const metadata = {
  title: "Watch Hub App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${atmaFont.variable} antialiased`}
      >
        <AuthContextProvider>
          {children}
          <ToastContainer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
